# Generated by Django 3.2.11 on 2022-04-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_product_item_prodct'),
        ('shop', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
