# Generated by Django 3.2.11 on 2022-07-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_product_item_prodct'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
